<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Phil McAleer">
  <title>Statistical Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #f8f8f2;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #f8f8f2; } /* Normal */
    code span.al { color: #f07178; } /* Alert */
    code span.an { color: #d4d0ab; } /* Annotation */
    code span.at { color: #00e0e0; } /* Attribute */
    code span.bn { color: #d4d0ab; } /* BaseN */
    code span.bu { color: #abe338; } /* BuiltIn */
    code span.cf { color: #ffa07a; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #abe338; } /* Char */
    code span.cn { color: #ffd700; } /* Constant */
    code span.co { color: #f8f8f2; font-style: italic; } /* Comment */
    code span.cv { color: #ffd700; } /* CommentVar */
    code span.do { color: #f8f8f2; } /* Documentation */
    code span.dt { color: #ffa07a; } /* DataType */
    code span.dv { color: #d4d0ab; } /* DecVal */
    code span.er { color: #f07178; text-decoration: underline; } /* Error */
    code span.ex { color: #00e0e0; font-weight: bold; } /* Extension */
    code span.fl { color: #d4d0ab; } /* Float */
    code span.fu { color: #ffa07a; } /* Function */
    code span.im { color: #abe338; } /* Import */
    code span.in { color: #d4d0ab; } /* Information */
    code span.kw { color: #ffa07a; font-weight: bold; } /* Keyword */
    code span.op { color: #ffa07a; } /* Operator */
    code span.ot { color: #00e0e0; } /* Other */
    code span.pp { color: #dcc6e0; } /* Preprocessor */
    code span.re { color: #00e0e0; background-color: #f8f8f2; } /* RegionMarker */
    code span.sc { color: #abe338; } /* SpecialChar */
    code span.ss { color: #abe338; } /* SpecialString */
    code span.st { color: #abe338; } /* String */
    code span.va { color: #00e0e0; } /* Variable */
    code span.vs { color: #abe338; } /* VerbatimString */
    code span.wa { color: #dcc6e0; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-327cab17de08e4a17faa7d61f48ae591.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="mermaid-theme" content="default">
  <script src="index_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="index_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="index_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Statistical Models</h1>
  <p class="subtitle">Lecture 1 - Introduction</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Phil McAleer 
</div>
<div class="quarto-title-author-email">
<a href="mailto:philip.mcaleer@glasgow.ac.uk">philip.mcaleer@glasgow.ac.uk</a>
</div>
        <p class="quarto-title-affiliation">
            University of Glasgow
          </p>
    </div>
</div>

</section>
<section id="todays-outline" class="slide level2">
<h2>Today’s Outline</h2>
<ol type="1">
<li>Why Models</li>
<li>Why Regression</li>
<li>This module</li>
</ol>
</section>
<section id="the-whole-picture" class="slide level2">
<h2>The whole picture</h2>
<ul>
<li>From Day 1 to now and beyond…</li>
</ul>
<p>Data Skills <span class="math inline">\(\Rightarrow\)</span> Analysis <span class="math inline">\(\Rightarrow\)</span> Psychometrics <span class="math inline">\(\Rightarrow\)</span> Models <span class="math inline">\(\Rightarrow\)</span> Advanced Options</p>
<ul>
<li>Start off with data skills (L1), working through some standard analytical approaches (L2), looked at scale development (L3 Sem 1), now statistical models (L3 Sem 2), with some more advanced options still to come (L4)</li>
</ul>
</section>
<section id="stat-models-an-overview-course" class="slide level2">
<h2>Stat models: An overview course</h2>
<p>Standing on top of everything and looking down, seeing all your different options and how to implement them <br><br> * Focus is on <strong>breadth</strong> rather than <strong>depth</strong> … except correlation &amp; regression, which provide the foundation for most advanced techniques <br><br> <strong>Aim:</strong> basic understanding of statistical models and the skills of how to implement them in R</p>
<ul>
<li>quite a practical module; reflected in the assignments</li>
</ul>
</section>
<section>
<section id="part-1-why-models" class="title-slide slide level1 center">
<h1>Part 1: Why models?</h1>

</section>
<section id="why-statistical-models" class="slide level2">
<h2>Why statistical models?</h2>
<div style="font-size: 90%;">
<ul>
<li>A statistical model is a <strong>simplification</strong> and <strong>idealization</strong> of reality that captures our key assumptions about how the data came about (the <strong>data generating process</strong> or <strong>DGP</strong>).</li>
<li>A statistical model is a “theory” about data and what drives the data we obtain! Models are just models; not the actual data!</li>
<li>A models importance is not in its veracity but in its ability to explain what we see!</li>
</ul>
<blockquote>
<p><em>“All models are wrong, but some are useful.”</em> - George Box</p>
</blockquote>
</div>
</section>
<section id="why-models" class="slide level2 center">
<h2>Why models?</h2>
<ol type="1">
<li>Models make things concrete</li>
<li>Models can help improve measurement</li>
<li>Models are flexible</li>
<li>Models can improve our inferences</li>
<li>Models can enable simulation</li>
</ol>
</section>
<section id="models-make-things-concrete" class="slide level2">
<h2>Models make things concrete</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/models-concrete.jpg"></p>
</div><div class="column" style="width:50%;">
<ul>
<li>Allow us to talk about things we can’t perceive</li>
<li>Force us to make our assumptions explicit</li>
<li>Clyde shipbuilders: talking to clients</li>
</ul>
</div></div>
<ul>
<li>Same with an analyses, if you present your underlying model of data to someone then the assumptions and layout of your idea behind the data is super clear and testable.</li>
</ul>
</section>
<section id="models-improve-measurement" class="slide level2">
<h2>Models improve measurement</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div id="happy-measurement">
<div>
<pre class="mermaid mermaid-js" data-label="happy-measurement">flowchart RL
  aC(("d")) --&gt; X1
  bC(("d")) --&gt; X2
  cC(("d")) --&gt; X3
  dC(("d")) --&gt; X4
  eC(("d")) --&gt; X5
  X1 &amp; X2 &amp; X3 &amp; X4 &amp; X5 --&gt; C(("life satisfaction"))
</pre>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Many concepts are ‘latent’ and cannot be observed in principle</li>
<li>observation = truth + error</li>
<li>Models can help differentiate the truth from the error and make better predictions, rather than just summing all the scores on a scale together.</li>
</ul>
</div></div>
</section>
<section id="models-are-flexible" class="slide level2">
<h2>Models are flexible</h2>
<p>… recipes aren’t!</p>
<ul>
<li>I am not a good cook. I open a box of eggs and think scrambled egg or omelette - maybe even some eggy bread if I am feeling dangerous.</li>
<li>My wife is an excellent cook and with one box of eggs she can make a whole world of meals, cakes and pastries.</li>
<li>My wife understands the models behind cooking and baking; I know a recipe!</li>
</ul>
</section>
<section id="contrast-recipes-are-not-models" class="slide level2">
<h2>Contrast: recipes are not models</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/studyres-com.png"></p>
</div><div class="column" style="width:50%;">
<ul>
<li>Standard approach to teaching statistics.</li>
<li>“If you have this, do this….”</li>
<li>Reasons to teach it but it is inflexible and easy to make mistakes like a wrong selection of data type</li>
<li>Knowing a recipe does not make you a chef.</li>
</ul>
</div></div>
<aside class="notes">
<ul>
<li>cooking analogy</li>
<li>punching buttons on a microwave (pre-packaged food)</li>
<li>versus taking fresh ingredients and improvising something</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="models-are-flexible-1" class="slide level2">
<h2>Models are flexible</h2>
<ul>
<li>Every study design and every resulting data set presents unique challenges to the analyst.</li>
</ul>
<blockquote>
<p>“If all you have is a hammer, everything looks like a nail”</p>
</blockquote>
<ul>
<li>Many of the studies we carry out are not as simple as one or two conditions on a single DV. Often you want to take into consideration multiple variables were some are continuous and some are categorical - e.g.&nbsp;the effects on reaction time of age and handedness!</li>
</ul>
<aside class="notes">
<ul>
<li><p>no study is exactly like any other, every dataset has unique properties</p></li>
<li><p>violation of assumptions</p>
<ul>
<li>especially: independence</li>
</ul></li>
<li><p>discretization of predictors</p></li>
<li><p>treating categorical data as continuous</p></li>
<li><p>over-aggregation</p></li>
<li><p>mindless statistics</p></li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="models-can-improve-our-inferences" class="slide level2">
<h2>Models can improve our inferences</h2>
<p>…and allow more nuanced questions</p>
<ul>
<li>The Stroop test is a classic psychological paradigm where participants are asked to respond to the color of a word, not the word themselves and we measure the reaction time.</li>
<li>Main effect is that when the word itself is a color word, then reaction time is much slower as you get a conflict between processes of reading and naming</li>
<li>Congruent: <span style="color:red;">red</span> - Incongruent: <span style="color:yellow;">red</span></li>
<li><span style="color:yellow;">red</span> would be slowest to react to because the color and word are incongruous</li>
</ul>
</section>
<section id="models-can-improve-our-inferences-1" class="slide level2">
<h2>Models can improve our inferences</h2>

<img data-src="img/models-improve-inferences.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>Rouder &amp; Haaf (2021) looked at two data sets of 121 and 264 participants to ask “Does everyone show the stroop effect?”</li>
<li>Each white ‘+’ is a participant. Each green circle is a model of that participant.</li>
</ul>
</section>
<section id="models-can-improve-our-inferences-2" class="slide level2">
<h2>Models can improve our inferences</h2>
<ul>
<li>In brief, Rouder &amp; Haaf (2021) found that just looking at the raw data suggests some do not show the stroop effect or even show the opposite effect - fast to name incongruous trials.</li>
<li>However, through modelling, and estimating each participants true effect through sampling more trials, then any unusual effects go away and every does indeed show the stroop effect.</li>
</ul>
</section>
<section id="models-can-improve-our-inferences-3" class="slide level2">
<h2>Models can improve our inferences</h2>

<img data-src="img/models-improve-inferences.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>Modelling allows us to get a more accurate representation of what is going on after accounting for error.</li>
</ul>
</section>
<section id="models-enable-simulation" class="slide level2">
<h2>Models enable simulation</h2>
<div style="font-size: 90%;">
<ul>
<li>Data simulation allows us to ask “what if?” questions
<ul>
<li>Think back to the model of the ship; what happens if I put it in this type of sea.</li>
<li>Same with data; what happens if I run the study like this or like that.</li>
</ul></li>
<li>Data simulation enables us to estimate power for complex analyses where closed-form solutions are unavailable
<ul>
<li>calculating power for things like t-tests, correlations, simple regression, etc, it becomes very difficult to estimate power for complex designs without models.</li>
<li>do I need more trials or more participants?</li>
</ul></li>
</ul>
</div>
</section></section>
<section>
<section id="part-2-why-regression" class="title-slide slide level1 center">
<h1>Part 2: Why Regression?</h1>

</section>
<section id="why-focus-on-regression" class="slide level2">
<h2>Why focus on Regression?</h2>
<p>Slight simplification: everything is just regression!</p>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>t-test</li>
<li>correlation &amp; regression</li>
<li>multiple regression</li>
<li>analysis of variance</li>
<li>linear mixed-effects modeling</li>
</ul>
</div><div class="column" style="width:40%;">
<ul>
<li>All are special cases of the General Linear Model (GLM).</li>
</ul>
</div></div>
</section>
<section id="glm-approach" class="slide level2">
<h2>GLM approach</h2>
<div style="font-size: 90%;">
<ol type="1">
<li>Define a mathematical model representing the processes that are assumed to give rise to the data
<ul>
<li>add, subtract, divide and multiply</li>
</ul></li>
<li>Estimate the parameters of the model
<ul>
<li>Parameters are values for different variables in the model</li>
</ul></li>
<li>Validate the model
<ul>
<li>does the model represent the data?</li>
</ul></li>
<li>Interpret the results</li>
<li>Transparently report what you did
<ul>
<li>share your code &amp; (anonymized) data</li>
</ul></li>
</ol>
</div>
</section>
<section id="example-parental-reflexes" class="slide level2">
<h2>Example: Parental reflexes</h2>
<div style="font-size: 90%;">
<p>Does being the parent of a toddler sharpen your reflexes?</p>
<ul>
<li>simple response time to a flashing light</li>
<li>dependent (response) variable: mean RT for each parent</li>
<li><span class="math inline">\(H_{0}: RT_{parents} = RT_{controls}\)</span></li>
<li><span class="math inline">\(H_{1}: RT_{parents} \neq RT_{controls}\)</span></li>
</ul>
<p>We will run this as a t-test, an ANOVA, and a regression to show you some connections!</p>
<ul>
<li>ANOVA (Analysis of Variance) - typically used when there are more than two conditions in an independent variable or more than two independent variables</li>
</ul>
</div>
</section>
<section id="simulating-data" class="slide level2">
<h2>Simulating Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1451</span>) <span class="co"># RNG seed: arbitrary integer value</span></span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>parents <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">480</span>, <span class="at">sd =</span> <span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>set.seed()</code> is a random number generator seed. You give it any value and every time you run a code that uses some form of data simulation, you get the same values</li>
<li>1451 here is arbitrary (other than the year the University was founded) but means if you run this code you will get same values.</li>
</ul>
</section>
<section id="simulating-data-1" class="slide level2">
<h2>Simulating Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1451</span>) <span class="co"># RNG seed: arbitrary integer value</span></span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a>parents <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">480</span>, <span class="at">sd =</span> <span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>rnorm()</code> is a function to create a set of random values (<code>r</code>) from the normal distribution (<code>norm</code>) given the <code>n</code> (number of data points, in this case 50), a <code>mean</code> (in this case, <span class="math inline">\(\mu\)</span> = 480), and a standard deviation (SD, in this case, <span class="math inline">\(\sigma\)</span> = 40).</li>
</ul>
</section>
<section id="simulating-data-2" class="slide level2">
<h2>Simulating data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1451</span>) <span class="co"># RNG seed: arbitrary integer value</span></span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>parents <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">480</span>, <span class="at">sd =</span> <span class="dv">40</span>)</span>
<span id="cb3-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="" aria-hidden="true" tabindex="-1"></a>parents</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 371.6093 441.0581 431.5599 500.2028 494.0001 559.8576 477.7761 438.0509
 [9] 419.6831 473.9525 567.7300 522.1104 515.5739 478.6110 489.2046 458.0759
[17] 409.6295 442.3012 569.0816 460.1299 536.3534 554.4357 499.2558 437.7825
[25] 394.8439 474.3383 470.9229 495.3417 524.6270 442.9606 473.4193 480.3155
[33] 524.6923 462.7873 425.7251 479.8248 530.8883 453.9530 452.5232 459.4812
[41] 483.1470 503.4610 503.3792 545.1496 477.1833 493.2693 461.2054 467.7529
[49] 524.6115 475.6842</code></pre>
</div>
</div>
<ul>
<li>n = 50, <span class="math inline">\(\mu\)</span> = 480 (mu, the mean), <span class="math inline">\(\sigma\)</span> = 40 (sigma, the standard deviation)</li>
<li>if you calculate values from data (mean, SD) they will not be exactly what you stated as it is partly random</li>
</ul>
</section>
<section id="control-group" class="slide level2">
<h2>Control group</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1451</span>) <span class="co"># RNG seed: arbitrary integer value</span></span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a>parents <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">480</span>, <span class="at">sd =</span> <span class="dv">40</span>)</span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a>parents</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 371.6093 441.0581 431.5599 500.2028 494.0001 559.8576 477.7761 438.0509
 [9] 419.6831 473.9525 567.7300 522.1104 515.5739 478.6110 489.2046 458.0759
[17] 409.6295 442.3012 569.0816 460.1299 536.3534 554.4357 499.2558 437.7825
[25] 394.8439 474.3383 470.9229 495.3417 524.6270 442.9606 473.4193 480.3155
[33] 524.6923 462.7873 425.7251 479.8248 530.8883 453.9530 452.5232 459.4812
[41] 483.1470 503.4610 503.3792 545.1496 477.1833 493.2693 461.2054 467.7529
[49] 524.6115 475.6842</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">500</span>, <span class="at">sd =</span> <span class="dv">40</span>)</span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a>control</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 532.8189 543.7581 528.3925 509.5635 453.8690 559.6398 540.3500 506.3915
 [9] 504.1397 515.3259 449.9757 406.2392 533.1140 468.4039 486.0484 546.7010
[17] 549.2453 449.2057 477.6283 591.3575 486.1334 510.9294 460.1222 516.6436
[25] 515.0298 494.2704 537.5971 511.3171 496.7403 472.8884 563.3012 501.2946
[33] 564.4603 522.0694 444.4553 512.0510 482.7866 563.2460 521.9919 521.8803
[41] 498.7435 453.5540 509.3144 513.5244 524.6281 470.4128 461.5146 485.6436
[49] 519.5610 453.9396</code></pre>
</div>
</div>
</section>
<section id="t-test-approach" class="slide level2">
<h2><span class="math inline">\(t\)</span>-test approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(parents, control, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  parents and control
t = -2.9687, df = 98, p-value = 0.00376
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -40.467066  -8.040887
sample estimates:
mean of x mean of y 
 480.5903  504.8443 </code></pre>
</div>
</div>
<ul>
<li>Outcome: t(98) = -2.9687, p = .00376.</li>
<li>The parent group (M = 480.5903) is significantly slower than the control group (M = 504.8443)</li>
</ul>
</section>
<section id="anova-approach" class="slide level2">
<h2>ANOVA approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"parent"</span>, <span class="st">"control"</span>), </span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(<span class="fu">length</span>(parents), <span class="fu">length</span>(control))),</span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">rt =</span> <span class="fu">c</span>(parents, control))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Here it is easier to work with the data in a <code>tibble()</code> (table)
<ul>
<li>Our <code>tibble()</code> has two columns:
<ul>
<li>group</li>
<li>rt</li>
</ul></li>
<li><code>rep()</code> says to copy the word “parent” for the number of parent values there are (<code>length(parents)</code>), and then do the same for <code>control</code></li>
</ul></li>
</ul>
</section>
<section id="anova-approach-1" class="slide level2">
<h2>ANOVA approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"parent"</span>, <span class="st">"control"</span>), </span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(<span class="fu">length</span>(parents), <span class="fu">length</span>(control))),</span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">rt =</span> <span class="fu">c</span>(parents, control))</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 2
   group     rt
   &lt;chr&gt;  &lt;dbl&gt;
 1 parent  372.
 2 parent  441.
 3 parent  432.
 4 parent  500.
 5 parent  494.
 6 parent  560.
 7 parent  478.
 8 parent  438.
 9 parent  420.
10 parent  474.
# ℹ 90 more rows</code></pre>
</div>
</div>
</section>
<section id="anova-approach-2" class="slide level2">
<h2>ANOVA approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a>mod_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(rt <span class="sc">~</span> group, dat)    </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>run the anova (<code>aov</code>) using the DV ~ IV approach
<ul>
<li><code>~</code>, tilde, means “by” in this context)</li>
<li><code>rt</code> is the DV, <code>group</code> is the IV, and the data is stored in <code>dat</code></li>
</ul></li>
</ul>
</section>
<section id="anova-approach-3" class="slide level2">
<h2>ANOVA approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_aov)    </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
group        1  14706   14706   8.813 0.00376 **
Residuals   98 163535    1669                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Outcome ANOVA: F(1,98) = 8.813, p = .00376</li>
<li>Outcome t-test: t(98) = -2.9687, p = .00376.
<ul>
<li>t<sup>2</sup> = -2.9687<sup>2</sup> = 8.81318</li>
<li>test values are related and dfs and p-values match</li>
</ul></li>
</ul>
</section>
<section id="regression" class="slide level2">
<h2>Regression</h2>
<div style="font-size: 90%;">
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + e_i\]</span> <span class="math display">\[Y_i = intercept + (slope \times X_i) + e_i\]</span> <span class="math display">\[e_i \sim N(0, \sigma^2)\]</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> - indicates the value of Y for the participant i</li>
<li>intercept - the value of Y when X is 0</li>
<li>slope - the change in Y for a 1 unit change in X</li>
<li><span class="math inline">\(e_i\)</span> - indicates the error for that participant at that value of Y, which are drawn overall from a Normal (<code>N</code>) distribution, with a mean of 0 and a given variance (<span class="math inline">\(\sigma^2\)</span>)</li>
</ul>
</div>
</section>
<section id="regression-approach" class="slide level2">
<h2>Regression Approach</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-10-1.png" width="960" class="r-stretch"><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(rt <span class="sc">~</span> group, dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Here we use the <code>lm()</code> (linear model) approach</li>
<li>Note that this approach enters groups in an alphabetical manner!</li>
</ul>
</section>
<section id="regression-approach-1" class="slide level2">
<h2>Regression Approach</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rt ~ group, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-108.98  -26.78   -0.49   23.04   88.49 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  504.844      5.777  87.388  &lt; 2e-16 ***
groupparent  -24.254      8.170  -2.969  0.00376 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 40.85 on 98 degrees of freedom
Multiple R-squared:  0.08251,   Adjusted R-squared:  0.07315 
F-statistic: 8.813 on 1 and 98 DF,  p-value: 0.00376</code></pre>
</div>
</div>
</section>
<section id="regression-approach-2" class="slide level2">
<h2>Regression Approach</h2>
<ul>
<li>Overall Model: F(1,98) = 8.813, p = .00376; same as t-test</li>
<li>Intercept: mean of control group, M = 504.844 (alphabetical entry)</li>
<li>“groupparent” coefficient: change in Y with a 1 unit change in X; go down 24.254 msecs - 504.844 - 24.254 = 480.59</li>
<li>t-value = -2.969, p = .00376; same as t-test</li>
<li>At least in the situation where there are only two groups, t-test, ANOVA and regression are identical in values and conclusions.</li>
</ul>
</section>
<section id="regression-is-flexible" class="slide level2">
<h2>Regression is Flexible</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">technique</th>
<th style="text-align: right;">t-test</th>
<th style="text-align: right;">ANOVA</th>
<th style="text-align: right;">regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Categorical IVs</td>
<td style="text-align: right;">✓</td>
<td style="text-align: right;">✓</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="even">
<td style="text-align: left;">Continuous DVs</td>
<td style="text-align: right;">✓</td>
<td style="text-align: right;">✓</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Continuous IVs</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multi-level data</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categorical DVs</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unbalanced data</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">✓</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&gt;1 sampling unit</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">✓</td>
</tr>
</tbody>
</table>
</section>
<section id="four-functions-to-rule-them-all" class="slide level2">
<h2>Four functions to rule them all</h2>
<ol type="1">
<li>Is the data single- or multi-level (i.e.&nbsp;one observation per participant or many)?</li>
<li>Is the response continuous or discrete?</li>
<li>How are the observations distributed?</li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">structure</th>
<th style="text-align: left;">response</th>
<th style="text-align: left;">distribution</th>
<th style="text-align: left;">R function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">single</td>
<td style="text-align: left;">cont</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;"><code>base::lm()</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">single</td>
<td style="text-align: left;">cont/disc</td>
<td style="text-align: left;">various</td>
<td style="text-align: left;"><code>base::glm()</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">multi</td>
<td style="text-align: left;">cont</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;"><code>lme4::lmer()</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">multi</td>
<td style="text-align: left;">cont/disc</td>
<td style="text-align: left;">various</td>
<td style="text-align: left;"><code>lme4::glmer()</code></td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="part-3-this-module" class="title-slide slide level1 center">
<h1>Part 3: This module!</h1>

</section>
<section id="section" class="slide level2 smaller">
<h2></h2>
<h4 id="part-1-phil-mcaleer-on-regression-multilevel-models-with-univariate-data"><span style="color:yellow;">Part 1: Phil McAleer on Regression &amp; multilevel models with univariate data</span></h4>
<table class="caption-top">
<thead>
<tr class="header">
<th>lecture</th>
<th>topic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>introduction</td>
</tr>
<tr class="even">
<td>2</td>
<td>correlation &amp; regression</td>
</tr>
<tr class="odd">
<td>3</td>
<td>multiple regression</td>
</tr>
<tr class="even">
<td>4</td>
<td>interactions</td>
</tr>
<tr class="odd">
<td>5</td>
<td>multilevel models</td>
</tr>
</tbody>
</table>
<h4 id="part-2-dale-barr-on-multivariate-models-psychometrics-more-than-one-dv-or-interlinked-variables"><span style="color:yellow;">Part 2: Dale Barr on Multivariate models &amp; psychometrics (more than one DV or interlinked variables)</span></h4>
<table class="caption-top">
<thead>
<tr class="header">
<th>lecture</th>
<th>topic (potential)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>6</td>
<td>introduction to multivariate data</td>
</tr>
<tr class="even">
<td>7</td>
<td>path analysis</td>
</tr>
<tr class="odd">
<td>8</td>
<td>mediation models</td>
</tr>
<tr class="even">
<td>9</td>
<td>confirmatory factor analysis</td>
</tr>
</tbody>
</table>
</section>
<section id="how-it-will-go" class="slide level2">
<h2>How it will go</h2>
<p>Course materials available on Moodle:</p>
<ul>
<li>Online book</li>
<li>Lecture slides &amp; recordings</li>
<li>Weekly formative exercises
<ul>
<li>download R Markdown ‘stub’ file and fill in with code</li>
</ul></li>
</ul>
<p>Complete the formative exercises <em>after</em> attending each lecture.</p>
<p>Read the corresponding book chapter before <em>before</em> attempting the formative assignment.</p>
</section>
<section id="formative-assignments" class="slide level2">
<h2>Formative assignments</h2>
<ul>
<li>Download the assignment files from Moodle<span class="math inline">\(^*\)</span></li>
<li>Fill your answers into the code chunks provided</li>
<li>Check for errors (knitting and validation)</li>
<li>Complete and submit the plain R Markdown file on Moodle before the due date</li>
<li>Compare your answers with the solution</li>
</ul>

<aside class="notes">
<p>due date: the day before the following lecture</p>
<p>solutions available: day of the following lecture</p>
<p>TODO: show an example for Formative 1</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside><div>
<p><span class="math inline">\(^*\)</span>Look for your assignment files under ‘feedback files’. One will be an R Markdown file (.Rmd). Others will be associated data files.</p>
</div></aside></section>
<section id="help-and-discussion" class="slide level2">
<h2>Help and discussion</h2>
<ul>
<li>My student drop-in hours:
<ul>
<li>58/60 Hillhead Street, Room 441</li>
<li>Tuesdays 3pm-5pm (normally)</li>
</ul></li>
<li>Microsoft Teams channel</li>
</ul>

<aside><div>
<p>Communication is important!</p>
<p>NB: If you have a question it is better to ask it on the Teams channel than by email/DM so that others can benefit</p>
</div></aside></section>
<section id="assessment" class="slide level2">
<h2>Assessment</h2>
<p>Two one-hour, timed, online assessments held during reading week and the week of the final lecture (dates on Moodle).</p>
<ul>
<li>First assessment: chapters/lectures 1-5</li>
<li>Second assessment: chapters/lectures 6-9</li>
</ul>
<p>Question format:</p>
<ul>
<li>Multiple choice / true-false questions</li>
<li>Variations on the formative exercises</li>
</ul>
</section>
<section id="hot-tip" class="slide level2">
<h2>Hot tip!</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Summative assessments will involve the same basic workflow as the formative assessments and the best way to prepare for the summative is to do the formative tasks. Completing the full workflow (including submission) for all the formative assessments is the best way to avoid nasty surprises.</p>
<p>You need to make sure you have the necessary technical resources including software ready to go in time for the assessment. Downloading packages, making sure things run and knit, etc.</p>
<p>Formative assignments are somewhat longer than the summative assignments but they are to give you the idea of what will happen. The summative assignments will be set to be very achievable in the duration of the test.</p>
</div>
</div>
</div>
</section>
<section id="for-next-week" class="slide level2">
<h2>For next week</h2>
<ul>
<li>Get your workstation in order
<ul>
<li>R version 4.1.0 or higher</li>
<li>R packages for analysis:
<ul>
<li><code>tidyverse</code>, <code>lme4</code>, <code>psych</code>, <code>corrr</code>, <code>lavaan</code></li>
</ul></li>
<li>R packages for working with R markdown
<ul>
<li><code>rmarkdown</code>, <code>knitr</code></li>
</ul></li>
</ul></li>
<li>Attempt formative assignment 1</li>
</ul>
</section></section>
<section id="next-week" class="title-slide slide level1 center">
<h1>Next Week</h1>
<p>Correlations and Simple Regression</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>