<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Phil McAleer">
  <title>Statistical Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #f8f8f2;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #f8f8f2; } /* Normal */
    code span.al { color: #f07178; } /* Alert */
    code span.an { color: #d4d0ab; } /* Annotation */
    code span.at { color: #00e0e0; } /* Attribute */
    code span.bn { color: #d4d0ab; } /* BaseN */
    code span.bu { color: #abe338; } /* BuiltIn */
    code span.cf { color: #ffa07a; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #abe338; } /* Char */
    code span.cn { color: #ffd700; } /* Constant */
    code span.co { color: #f8f8f2; font-style: italic; } /* Comment */
    code span.cv { color: #ffd700; } /* CommentVar */
    code span.do { color: #f8f8f2; } /* Documentation */
    code span.dt { color: #ffa07a; } /* DataType */
    code span.dv { color: #d4d0ab; } /* DecVal */
    code span.er { color: #f07178; text-decoration: underline; } /* Error */
    code span.ex { color: #00e0e0; font-weight: bold; } /* Extension */
    code span.fl { color: #d4d0ab; } /* Float */
    code span.fu { color: #ffa07a; } /* Function */
    code span.im { color: #abe338; } /* Import */
    code span.in { color: #d4d0ab; } /* Information */
    code span.kw { color: #ffa07a; font-weight: bold; } /* Keyword */
    code span.op { color: #ffa07a; } /* Operator */
    code span.ot { color: #00e0e0; } /* Other */
    code span.pp { color: #dcc6e0; } /* Preprocessor */
    code span.re { color: #00e0e0; background-color: #f8f8f2; } /* RegionMarker */
    code span.sc { color: #abe338; } /* SpecialChar */
    code span.ss { color: #abe338; } /* SpecialString */
    code span.st { color: #abe338; } /* String */
    code span.va { color: #00e0e0; } /* Variable */
    code span.vs { color: #abe338; } /* VerbatimString */
    code span.wa { color: #dcc6e0; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-327cab17de08e4a17faa7d61f48ae591.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Statistical Models</h1>
  <p class="subtitle">Lecture 5 - Linear Mixed Effects Models</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Phil McAleer 
</div>
<div class="quarto-title-author-email">
<a href="mailto:philip.mcaleer@glasgow.ac.uk">philip.mcaleer@glasgow.ac.uk</a>
</div>
        <p class="quarto-title-affiliation">
            University of Glasgow
          </p>
    </div>
</div>

</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li>introduction to <strong>linear mixed-effects modeling</strong></li>
<li>example: sleepstudy data (Belenky et al, 2003)
<ul>
<li>distinguish complete pooling, no pooling and partial pooling approaches</li>
</ul></li>
<li>understand the Data Generation Process (DGP) behind multi-level data and estimation with <code>lme4::lmer()</code>
<ul>
<li><code>lm()</code> - linear model</li>
<li><code>lmer()</code> - linear mixed effects regression
<ul>
<li>need to <code>install.packages("lme4")</code> first time.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="single-level-vs-multi-level" class="slide level2">
<h2>Single-level vs Multi-level</h2>
<ul>
<li>Single-level means we have one observation or one data point per sampling unit
<ul>
<li>one response from each participant/stimuli</li>
</ul></li>
<li>Multi-level means we have more than one observation or data point per sampling unit
<ul>
<li>more than one response from each participant/stimuli</li>
</ul></li>
<li>Both, in today’s context, are still univariate in that they are only interested in one DV.</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li>All the techniques we have looked at over past 5 weeks are still part of the General Linear Model and effectively regression
<ul>
<li>t-test, correlations, anovas, simple regression, multiple regression, linear mixed effects models</li>
<li>the underlying basis of <span class="math inline">\(\hat{Y} = \beta_0 + \beta_1 \times X\)</span> applies across all</li>
<li>the complexity within the models has been increasing as we have gone through them but to paraphrase “with greater complexity, comes greater power!”</li>
</ul></li>
</ul>
</section>
<section id="multilevel-data" class="slide level2">
<h2>Multilevel data</h2>
<ul>
<li>All parametric models assume model residuals are IID (“independently and identically distributed”) which won’t be the case when you have multiple observations per sampling unit (e.g.&nbsp;participant).</li>
<li>Data often has ‘clusters’ of correlated observations due to
<ul>
<li>multistage sampleing &amp; natural clustering</li>
<li>for example, individual differences in reaction time will be smaller within a participant than across participants.</li>
</ul></li>
</ul>
</section>
<section id="pros-and-cons-of-lmems" class="slide level2">
<h2>pros and cons of LMEMs</h2>
<p><strong>Cons</strong></p>
<ul>
<li>Complex</li>
<li>Estimated iteratively and may not converge!</li>
</ul>
<p><strong>Convergence</strong></p>
<ul>
<li>Unlike simple regression, which will always give a solution based on the formula, LMEMs are an algorithmic interative process based on finding the best soltuion to the parameter estimates (e.g.&nbsp;<span class="math inline">\(\beta\)</span>). When it does this it is said to converge.</li>
</ul>
</section>
<section id="pros-and-cons-of-lmems-1" class="slide level2">
<h2>pros and cons of LMEMs</h2>
<p><strong>Pros</strong></p>
<ul>
<li>powerful and expressive</li>
<li>modeling of continuous &amp; categorical predictors</li>
<li>unbalanced/missing data (partial pooling)</li>
<li>discrete DVs and/or non-normal distributions</li>
<li>multiple random factors</li>
</ul>
</section>
<section id="random-vs-fixed-factors" class="slide level2">
<h2>Random vs Fixed Factors</h2>
<ul>
<li>until now we have assumed fixed factors - the value of the estimate wont change across sampling unit (e.g.&nbsp;participants)</li>
<li>not always the case and often we know there will be variation</li>
<li>LMEMs all us to state some factors as random meaning we expect some variation</li>
<li>helps improve generalisability of the findings</li>
</ul>
</section>
<section id="random-vs-fixed-factors-1" class="slide level2 smaller">
<h2>Random vs Fixed Factors</h2>
<ul>
<li>more often than not you expect participants to have variation, not just within your sample but also from your sample to the population.</li>
<li>same with faces, voices, and a whole host of stimuli</li>
<li>Distinction can come from if you care only about the participants/stimuli used (fixed) or about all possible participants/stimuli in that factor (random)
<ul>
<li>a study to compare engagement of art masterpieces using the Mona Lisa (random)</li>
<li>a study to compare engagement with the Mona Lisa (fixed)</li>
</ul></li>
<li><strong>exchangability</strong> - does it matter what is labelled as Participant 1 or Stim 1.
<ul>
<li>if it does not matter, then random factor</li>
<li>if it does matter, then fixed factor</li>
</ul></li>
</ul>
</section>
<section>
<section id="understanding-multi-level-modeling" class="title-slide slide level1 center">
<h1>Understanding multi-level modeling</h1>

</section>
<section id="belenky-et-al.-2003" class="slide level2">
<h2>Belenky et al.&nbsp;(2003)</h2>
<p>Worked example: Belenky et al.&nbsp;(2003) <code>sleepstudy</code> data used in formative 2 of this module; in the <code>lme4</code> package.</p>

<img data-src="sleepstudy_article.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="belenky-et-al.-2003-1" class="slide level2">
<h2>Belenky et al.&nbsp;(2003)</h2>
<p><strong>Abstract:</strong> Daytime performance changes were examined during chronic sleep restriction or augmentation and following subsequent recovery sleep. Sixty-six normal volunteers spent either 3 (n = 18), 5 (n= 16), 7 (n = 16), or 9 h (n = 16) daily time in bed (TIB) for 7 days (restriction/augmentation) followed by 3 days with 8 h daily TIB (recovery). In the 3-h group, speed (mean and fastest 10% of responses) on the psychomotor vigilance task (PVT) declined, and PVT lapses (reaction times greater than 500 ms) increased steadily across the 7 days of sleep restriction…</p>

<aside class="notes">
<p>From paper: The PVT measures simple reaction time to a visual stimulus, presented approximately 10times/minute (interstimulus interval varied from 2 to 10s in 2-s increments) for 10min and implemented in a thumb-operated, hand-held device (Dinges and Powell 1985).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside><div>
<p><a href="https://pubmed.ncbi.nlm.nih.gov/12603781/" target="_blank">Link to Paper</a></p>
</div></aside></section>
<section id="belenky-et-al.-2003-2" class="slide level2">
<h2>Belenky et al.&nbsp;(2003)</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"><ul>
<li>observations within each subject show some relationship</li>
<li>violates assumption of independence of data points</li>
</ul>
</section>
<section id="approaches-to-multi-level-data" class="slide level2">
<h2>Approaches to Multi-level data</h2>
<ol type="1">
<li>complete pooling
<ul>
<li>ignore dependencies in the data</li>
</ul></li>
<li>no pooling
<ul>
<li>account for dependencies by fitting each subject independently</li>
</ul></li>
<li>partial pooling
<ul>
<li>account for dependencies by explicitly modeling them</li>
<li>fit for each subject informed by the fits for other subjects</li>
</ul></li>
</ol>
</section>
<section id="complete-pooling" class="slide level2">
<h2>Complete Pooling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Reaction <span class="sc">~</span> Days, <span class="at">data =</span> sleepstudy)</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># gives same intercept and slope (blue line) to all</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<img data-src="completepooling.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>each facet is a participant; each dot an RT on sequential days; blue line is estimated line from complete pooling; dashed black line is true relationship in each participant</li>
<li>fit is not good</li>
</ul>
</section>
<section id="no-pooling" class="slide level2">
<h2>No Pooling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Reaction <span class="sc">~</span> Days <span class="sc">*</span> Subjects, <span class="at">data =</span> sleepstudy)</span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># gives different intercept and slope (blue line) to each participant </span></span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Uses one participant as baseline</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<img data-src="nopooling.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>fit is much better (blue and black sit much closer)</li>
<li>however doesn’t give an “overall” as everything is relative to baseline</li>
</ul>
</section>
<section id="no-pooling-1" class="slide level2 smaller">
<h2>No Pooling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> Days <span class="sc">*</span> Subject, <span class="at">data =</span> sleepstudy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Reaction ~ Days * Subject, data = sleepstudy)

Residuals:
     Min       1Q   Median       3Q      Max 
-106.397  -10.692   -0.177   11.417  132.510 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      244.193     15.042  16.234  &lt; 2e-16 ***
Days              21.765      2.818   7.725 1.74e-12 ***
Subject309       -39.138     21.272  -1.840 0.067848 .  
Subject310       -40.708     21.272  -1.914 0.057643 .  
Subject330        45.492     21.272   2.139 0.034156 *  
Subject331        41.546     21.272   1.953 0.052749 .  
Subject332        20.059     21.272   0.943 0.347277    
Subject333        30.826     21.272   1.449 0.149471    
Subject334        -4.030     21.272  -0.189 0.850016    
Subject335        18.842     21.272   0.886 0.377224    
Subject337        45.911     21.272   2.158 0.032563 *  
Subject349       -29.081     21.272  -1.367 0.173728    
Subject350       -18.358     21.272  -0.863 0.389568    
Subject351        16.954     21.272   0.797 0.426751    
Subject352        32.179     21.272   1.513 0.132535    
Subject369        10.775     21.272   0.507 0.613243    
Subject370       -33.744     21.272  -1.586 0.114870    
Subject371         9.443     21.272   0.444 0.657759    
Subject372        22.852     21.272   1.074 0.284497    
Days:Subject309  -19.503      3.985  -4.895 2.61e-06 ***
Days:Subject310  -15.650      3.985  -3.928 0.000133 ***
Days:Subject330  -18.757      3.985  -4.707 5.84e-06 ***
Days:Subject331  -16.499      3.985  -4.141 5.88e-05 ***
Days:Subject332  -12.198      3.985  -3.061 0.002630 ** 
Days:Subject333  -12.623      3.985  -3.168 0.001876 ** 
Days:Subject334   -9.512      3.985  -2.387 0.018282 *  
Days:Subject335  -24.646      3.985  -6.185 6.07e-09 ***
Days:Subject337   -2.739      3.985  -0.687 0.492986    
Days:Subject349   -8.271      3.985  -2.076 0.039704 *  
Days:Subject350   -2.261      3.985  -0.567 0.571360    
Days:Subject351  -15.331      3.985  -3.848 0.000179 ***
Days:Subject352   -8.198      3.985  -2.057 0.041448 *  
Days:Subject369  -10.417      3.985  -2.614 0.009895 ** 
Days:Subject370   -3.709      3.985  -0.931 0.353560    
Days:Subject371  -12.576      3.985  -3.156 0.001947 ** 
Days:Subject372  -10.467      3.985  -2.627 0.009554 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.59 on 144 degrees of freedom
Multiple R-squared:  0.8339,    Adjusted R-squared:  0.7936 
F-statistic: 20.66 on 35 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>generates an intercept and slope coefficient for all subjects where the values are the offset to the baseline participant</li>
<li>e.g.&nbsp;244 is mean RT of Subject 308 (baseline) and 244 + (-39.138) is intercept for Subject 309.</li>
<li>hard to interpret</li>
<li>would need to then do something with all values to establish effect or not.</li>
</ul>
</div></div>
</section>
<section id="partial-pooling" class="slide level2 smaller">
<h2>Partial Pooling</h2>

<img data-src="partialpooling.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>as good as no pooling but as well as fitting individual slopes and intercepts per participant, it makes and adjustment to each participant based on the other participants</li>
<li>takes into consideration that similarity in samples (e.g.&nbsp;students within a classroom)</li>
<li>gives an overall effect (fixed effect) and an effect for variation (random effect)</li>
</ul>
</section></section>
<section>
<section id="dgp-and-estimation" class="title-slide slide level1 center">
<h1>DGP and estimation</h1>

</section>
<section id="glm-for-sleepstudy" class="slide level2">
<h2>GLM for sleepstudy</h2>
<p><em>Level 1:</em></p>
<p><span class="math display">\[Y_{ij} = \beta_0 + \beta_1 X_{ij} + e_{ij}\]</span></p>
<p><em>Level 2:</em></p>
<p><span class="math display">\[\beta_0 = \gamma_{00} + S_{0i}\]</span></p>
<p><span class="math display">\[\beta_1 = \gamma_{10} + S_{1i}\]</span></p>
</section>
<section id="glm-for-sleepstudy-1" class="slide level2">
<h2>GLM for sleepstudy</h2>
<p><em>Level 1:</em></p>
<p><span class="math display">\[Y_{ij} = \beta_0 + \beta_1 X_{ij} + e_{ij}\]</span></p>
<ul>
<li><span class="math inline">\(Y_{ij}\)</span> is the predicted reaction time (Y) for a given participant (i) on a given day (j)</li>
<li>So if you new the intercept and slope, and if X was say day 1, then: intercept + slope <span class="math inline">\(\times\)</span> 1 = Y</li>
</ul>
</section>
<section class="slide level2">

<p><em>Level 2: New part</em></p>
<p><span class="math display">\[\beta_0 = \gamma_{00} + S_{0i}\]</span></p>
<ul>
<li>Intercept (<span class="math inline">\(\beta_0\)</span>) is made up of a fixed effect (<span class="math inline">\(\gamma_{00}\)</span>, gamma zero zero) and a random effect (<span class="math inline">\(S_{0i}\)</span>, S zero i)</li>
<li>The fixed effect (<span class="math inline">\(\gamma_{00}\)</span>, gamma zero zero) is the overall intercept (e.g.&nbsp;overall mean reaction time)</li>
<li>The random effect (<span class="math inline">\(S_{0i}\)</span>, S zero i) is the intercept offset to take into account the variation across participants. One random intercept per participant.</li>
</ul>
</section>
<section class="slide level2">

<p><span class="math display">\[\beta_1 = \gamma_{10} + S_{1i}\]</span></p>
<ul>
<li>Slope (<span class="math inline">\(\beta_1\)</span>) is made up of a fixed effect (<span class="math inline">\(\gamma_{10}\)</span>, gamma one zero) and a random effect (<span class="math inline">\(S_{1i}\)</span>, S one i)</li>
<li>The fixed effect (<span class="math inline">\(\gamma_{10}\)</span>, gamma one zero) is the overall slope (e.g.&nbsp;overall relationship between days and RT)</li>
<li>The random effect (<span class="math inline">\(S_{1i}\)</span>, S one i) is the slope offset to take into account the variation across participants. One random slope per participant.</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li>linear model</li>
</ul>
<p><span class="math display">\[Y_{ij} = \beta_0 + \beta_1 X_{ij} + e_{ij}\]</span></p>
<ul>
<li>linear mixed effects model</li>
</ul>
<p><span class="math display">\[Y_{ij} = (\gamma_{00} + S_{0i}) + (\gamma_{10} + S_{1i}) X_{ij} + e_{ij}\]</span></p>
<ul>
<li>But everything is still just Y equals intercept plus slope times X plus error, just in LMEM the intercept and slope are made up of a fixed and random effect each.</li>
</ul>
</section>
<section class="slide level2">

<p>Made up example:</p>
<ul>
<li>Participant 1, Day 5</li>
<li>overall intercept (mean RT) = 250 msecs</li>
<li>intercept offset for participant 1 = 20 msecs</li>
<li>overall slope (relationship) = 10</li>
<li>slope offset for participant 1 = 8</li>
</ul>
<p><span class="math display">\[Y_{ij} = (\gamma_{00} + S_{0i}) + (\gamma_{10} + S_{1i}) X_{ij} + e_{ij}\]</span></p>
<p><span class="math display">\[Y_{ij} = (250 + 20) + (10 + 8) \times 5 = 360\]</span></p>
</section>
<section class="slide level2">

<p>Made up example:</p>
<ul>
<li>Participant 1, Group 1 where Group 1 is coded as 0.5 (<span class="math inline">\(\frac{1}{2}\)</span>)</li>
<li>overall intercept (mean RT) = 250 msecs</li>
<li>intercept offset for participant 1 = 20 msecs</li>
<li>overall slope (relationship) = 10</li>
<li>slope offset for participant 1 = 8</li>
</ul>
<p><span class="math display">\[Y_{ij} = (\gamma_{00} + S_{0i}) + (\gamma_{10} + S_{1i}) X_{ij} + e_{ik}\]</span></p>
<p><span class="math display">\[Y_{ij} = (250 + 20) + (10 + 8) \times .5 = 279\]</span></p>
</section>
<section id="variance-components" class="slide level2 smaller">
<h2>Variance Components</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[\left&lt; S_{0i}, S_{1i} \right&gt; \sim N(\left&lt; 0, 0 \right&gt;, \mathbf{\Sigma})\]</span></p>
<p><span class="math display">\[\mathbf \Sigma = \left(
  \begin{array}{cc}
  {\tau_{00}}^2 &amp; \rho\tau_{00}\tau_{11} \\
  \rho\tau_{00}\tau_{11} &amp; {\tau_{11}}^2 \\
  \end{array} \right)\]</span></p>
<p><span class="math display">\[e_{ij} \sim N(0, \sigma^2)\]</span></p>

</div><div class="column" style="width:50%;">
<ul>
<li>the random intercept (<span class="math inline">\(S_{0i}\)</span>) and slope (<span class="math inline">\(S_{1i}\)</span>) are estimated from a Normal Distribution (<span class="math inline">\(N\)</span>) with means of 0, and covariance of sigma (<span class="math inline">\(\Sigma\)</span>)</li>
<li>sigma (<span class="math inline">\(\Sigma\)</span>) is a covariance matrix of the intercept variance (<span class="math inline">\({\tau_{00}}^2\)</span>), the slope variance(<span class="math inline">\({\tau_{11}}^2\)</span>), and the covariance of the slope and intercept (<span class="math inline">\(\rho\tau_{00}\tau_{11}\)</span>)</li>
</ul>
</div></div>
<aside><div>
<ul>
<li><span class="math inline">\(\tau\)</span> pronounced tau or “tow” as in “town”</li>
<li><span class="math inline">\(\rho\)</span> is the correlation symbol</li>
</ul>
</div></aside></section>
<section id="variance-components-1" class="slide level2">
<h2>Variance Components</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[\left&lt; S_{0i}, S_{1i} \right&gt; \sim N(\left&lt; 0, 0 \right&gt;, \mathbf{\Sigma})\]</span></p>
<p><span class="math display">\[\mathbf \Sigma = \left(
  \begin{array}{cc}
  {\tau_{00}}^2 &amp; \rho\tau_{00}\tau_{11} \\
  \rho\tau_{00}\tau_{11} &amp; {\tau_{11}}^2 \\
  \end{array} \right)\]</span></p>
<p><span class="math display">\[e_{ij} \sim N(0, \sigma^2)\]</span></p>
</div><div class="column" style="width:50%;">
<p>LMEM is effectively estimating The Variance Components:</p>
<ul>
<li><span class="math inline">\({\tau_{00}}^2\)</span> - intercept variance</li>
<li><span class="math inline">\({\tau_{11}}^2\)</span> - slope variance</li>
<li><span class="math inline">\(\rho\)</span> - correlation between slope and intercept</li>
<li><span class="math inline">\(\sigma^2\)</span> - variance in error</li>
</ul>
</div></div>
</section>
<section id="section" class="slide level2">
<h2></h2>
<div class="cell">
<iframe src="https://dalejbarr.github.io/statistical-models-web-apps/multilevel-site?showcase=0" width="960" height="700px" data-external="1">
</iframe>
</div>
<p><a href="https://dalejbarr.github.io/statistical-models-web-apps/multilevel-site" target="_blank">Go To App</a></p>
</section>
<section id="estimation" class="slide level2 smaller">
<h2>Estimation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lme4"</span>)</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">|</span> Subject), </span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> sleepstudy)</span>
<span id="cb5-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>funtion: <code>lmer()</code></li>
<li><code>Reaction ~ Days</code> is common syntax by now</li>
<li><code>(Days | Subjects)</code> says let effect of days vary across subjects. This is actually the syntax for a random slope; must be within brackets.</li>
<li>Don’t need to say give random intercept as well as it is implied but would be written as <code>(1 | Subjects)</code></li>
<li>So <code>(1 + Days | Subjects)</code> says give me random intercepts and slopes and is same as <code>(Days | Subjects)</code></li>
</ul>
</section>
<section id="estimation-1" class="slide level2 smaller">
<h2>Estimation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Reaction ~ Days + (Days | Subject)
   Data: sleepstudy

REML criterion at convergence: 1743.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.9536 -0.4634  0.0231  0.4634  5.1793 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 Subject  (Intercept) 612.10   24.741       
          Days         35.07    5.922   0.07
 Residual             654.94   25.592       
Number of obs: 180, groups:  Subject, 18

Fixed effects:
            Estimate Std. Error t value
(Intercept)  251.405      6.825  36.838
Days          10.467      1.546   6.771

Correlation of Fixed Effects:
     (Intr)
Days -0.138</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Output:</p>
<ul>
<li>REML = Restricted Maximum Likelihood</li>
<li><span class="math inline">\(\gamma_{00}\)</span> = 251.405</li>
<li><span class="math inline">\(\gamma_{10}\)</span> = 10.467</li>
<li><span class="math inline">\({\tau_{00}}^2\)</span> = 612.10</li>
<li><span class="math inline">\({\tau_{11}}^2\)</span> = 35.07</li>
<li><span class="math inline">\(\rho\)</span> = .07</li>
<li><span class="math inline">\(\sigma^2\)</span> = 654.94</li>
<li><span class="math inline">\(\sigma\)</span> = 25.692</li>
<li><span class="math inline">\(cov\)</span> = .07 * 24.741 * 5.922</li>
</ul>
</div></div>
</section>
<section id="model-syntax" class="slide level2 smaller">
<h2>model syntax</h2>
<p><code>DV ~ iv1 + iv2 + (iv1 | random_factor)</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Subject), sleepstudy) <span class="co"># (1) random intercept</span></span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">|</span> Subject), sleepstudy) <span class="co"># (2) random slope model.</span></span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">|</span> Subject), sleepstudy) <span class="co"># (3) identical to (2)</span></span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Subject) <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> Days <span class="sc">|</span> Subject)) <span class="co"># (4) zero-covariances</span></span>
<span id="cb7-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">||</span> Subject), sleepstudy) <span class="co"># (5) identical to (4)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>(1)</code> seems a bit redundant because if you think the intercept is going to vary then the slope will vary too</li>
<li><code>(2)</code> and <code>(3)</code> are the same, random slope and random intercepts. Most common approach.</li>
<li><code>(4)</code> and <code>(5)</code> are identical and says assume no correlation - so same intercept but different slopes</li>
</ul>
</section>
<section id="p-values-model-comparison" class="slide level2 smaller">
<h2>p-values: model comparison</h2>

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a>mod_base <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> (Days <span class="sc">|</span> Subject),</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a>             sleepstudy, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">|</span> Subject),</span>
<span id="cb8-4"><a href="" aria-hidden="true" tabindex="-1"></a>             sleepstudy, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="do">## or:</span></span>
<span id="cb8-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="do">## mod2 &lt;- update(mod1, . ~ . -Days)</span></span>
<span id="cb8-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_base, mod_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Create two models.
<ul>
<li>One with the fixed effect (<code>mod_full</code>) and one without the fixed effect (<code>mod_base</code>).</li>
</ul></li>
<li>Idea is saying “accounting for all the random variation within the data, is there still a significant fixed effect”.</li>
<li><span class="math inline">\(H_0\)</span>: mod_full <span class="math inline">\(=\)</span> mod_base</li>
<li><span class="math inline">\(H_1\)</span>: mod_full <span class="math inline">\(\ne\)</span> mod_base</li>
</ul>
<aside><div>
<p>NB: use <code>REML=FALSE</code>; comparison will then use Maximum Likelihood (ML) and give a better estimate of p-value.</p>
</div></aside></section>
<section id="p-values-model-comparison-1" class="slide level2 smaller">
<h2>p-values: model comparison</h2>

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a>mod_base <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> (Days <span class="sc">|</span> Subject),</span>
<span id="cb9-2"><a href="" aria-hidden="true" tabindex="-1"></a>             sleepstudy, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> Days <span class="sc">+</span> (Days <span class="sc">|</span> Subject),</span>
<span id="cb9-4"><a href="" aria-hidden="true" tabindex="-1"></a>             sleepstudy, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="do">## or:</span></span>
<span id="cb9-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="do">## mod2 &lt;- update(mod1, . ~ . -Days)</span></span>
<span id="cb9-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_base, mod_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
   npar   AIC   BIC logLik `-2*log(L)` Chisq    Df `Pr(&gt;Chisq)`
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;
1     5 1785. 1801.  -888.       1775.  NA      NA  NA         
2     6 1764. 1783.  -876.       1752.  23.5     1   0.00000123</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\chi^2\)</span>(1) = 23.5, p &lt; .001</li>
<li>so yes there was a significant effect.</li>
</ul>
<aside><div>
<p>NB: use <code>REML=FALSE</code>; comparison will then use Maximum Likelihood (ML) and give a better estimate of p-value.</p>
</div></aside></section></section>
<section id="thats-all-folks" class="title-slide slide level1 center">
<h1>That’s all folks!</h1>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>